/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Vector;
import javax.swing.JOptionPane;
import utils.ipaddr;

/**
 *
 * @author Lenovo
 */
public class deletefile extends javax.swing.JFrame {

    /**
     * Creates new form deletefile
     */
    String uname;
    
    public deletefile(String user) {
        this.uname=user;
        initComponents();
        jLabel2.setText("Logged in as "+user);
        getfiles();
    }
    
    void getfiles()
    {
        try
        {
            Socket soc=new Socket(utils.ipaddr.cloudip,utils.ipaddr.cloudport);
                ObjectOutputStream oos=new ObjectOutputStream(soc.getOutputStream());
                ObjectInputStream oin=new ObjectInputStream(soc.getInputStream());
                    
                oos.writeObject("GETFILES");
                oos.writeObject(uname);
                String reply=(String)oin.readObject();
                jComboBox1.removeAllItems();
                if (reply.equals("SUCCESS"))
                {
                   Vector v=(Vector)oin.readObject();
                   for (int i=0;i<v.size();i++)
                   jComboBox1.addItem(v.get(i).toString().trim());
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"No files found!");
                }
        }
        catch(Exception e)
        {
            System.out.println(e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DELETE FILE");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Select File");

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(0, 143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            if (jComboBox1.getSelectedIndex()!=-1)
            {
                String fname=jComboBox1.getSelectedItem().toString().trim();
                
                int m=JOptionPane.showConfirmDialog(this,"Are you sure to delete file "+fname+"?");
                
                if (m==JOptionPane.OK_OPTION)
                {    
                Socket soc=new Socket(utils.ipaddr.cloudip,utils.ipaddr.cloudport);
                ObjectOutputStream oos=new ObjectOutputStream(soc.getOutputStream());
                ObjectInputStream oin=new ObjectInputStream(soc.getInputStream());
                    
                oos.writeObject("DELETE");
                oos.writeObject(uname);
                oos.writeObject(fname);
                String reply=(String)oin.readObject();
                    
                if (reply.equals("SUCCESS"))
                {
                    JOptionPane.showMessageDialog(this, "File Successfully deleted!");
                    String reply1=new sendblock().addblock(uname,"DELETE",fname);
                      
                    if (reply1.equals("SUCCESS")) //block added in blockchain server
                       JOptionPane.showMessageDialog(this,"Block successfully added to blockchain server!");
                    else
                       JOptionPane.showMessageDialog(this,"Block creation failed!");
                    
                    getfiles();
                        
                        
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error while deleting file!");
                }
                
                oos.close();
                oin.close();
                 soc.close();
                }
                else
                {
                     JOptionPane.showMessageDialog(this,"Delete operation cancelled!");
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Select file first!");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
