/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class editfile extends javax.swing.JFrame {

    /**
     * Creates new form deletefile
     */
    String uname;
    
    public editfile(String user) {
        this.uname=user;
        initComponents();
        jLabel2.setText("Logged in as "+user);
        getfiles();
    }
    
    void getfiles()
    {
        try
        {
            Socket soc=new Socket(utils.ipaddr.cloudip,utils.ipaddr.cloudport);
                ObjectOutputStream oos=new ObjectOutputStream(soc.getOutputStream());
                ObjectInputStream oin=new ObjectInputStream(soc.getInputStream());
                    
                oos.writeObject("GETFILES");
                oos.writeObject(uname);
                String reply=(String)oin.readObject();
                if (reply.equals("SUCCESS"))
                {
                   Vector v=(Vector)oin.readObject();
                   jComboBox1.addItem("SELECT");
                   for (int i=0;i<v.size();i++)
                   jComboBox1.addItem(v.get(i).toString().trim());
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"No files found!");
                }
        }
        catch(Exception e)
        {
            System.out.println(e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT FILE");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Select File");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("DOWNLOAD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            if (jComboBox1.getSelectedIndex()!=-1)
            {
                String fname=jComboBox1.getSelectedItem().toString().trim();
                
                if (jTextArea1.getText().trim().equals(""))
                {
                    JOptionPane.showMessageDialog(this,"File content cannot be empty!");
                }
                else
                {    
                int m=JOptionPane.showConfirmDialog(this,"Are you sure to save file "+fname+"?");
                
                if (m==JOptionPane.OK_OPTION)
                {    
                Socket soc=new Socket(utils.ipaddr.cloudip,utils.ipaddr.cloudport);
                ObjectOutputStream oos=new ObjectOutputStream(soc.getOutputStream());
                ObjectInputStream oin=new ObjectInputStream(soc.getInputStream());
                    
                oos.writeObject("SAVE");
                oos.writeObject(uname);
                oos.writeObject(fname);
                oos.writeObject(jTextArea1.getText().trim().getBytes());
                String reply=(String)oin.readObject();
                    
                if (reply.equals("SUCCESS"))
                {
                    JOptionPane.showMessageDialog(this, "File Successfully saved to cloud!");
                    String reply1=new sendblock().addblock(uname,"EDIT",fname);
                      
                    if (reply1.equals("SUCCESS")) //block added in blockchain server
                       JOptionPane.showMessageDialog(this,"Block successfully added to blockchain server!");
                    else
                       JOptionPane.showMessageDialog(this,"Block creation failed!");
                        
                        
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error while saving file!");
                }
                
                oos.close();
                oin.close();
                 soc.close();
                }
                else
                {
                     JOptionPane.showMessageDialog(this,"Edit operation cancelled!");
                }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Select file first!");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try
        {
           if (jComboBox1.getSelectedIndex()>0)
           {
               String fname=jComboBox1.getSelectedItem().toString().trim();
               
               Socket soc=new Socket(utils.ipaddr.cloudip,utils.ipaddr.cloudport);
                ObjectOutputStream oos=new ObjectOutputStream(soc.getOutputStream());
                ObjectInputStream oin=new ObjectInputStream(soc.getInputStream());
                    
                oos.writeObject("EDIT");
                oos.writeObject(uname);
                oos.writeObject(fname);
                String reply=(String)oin.readObject();
                    
                if (reply.equals("SUCCESS"))
                {
                    byte b[]=(byte[])oin.readObject();
                    
                    jTextArea1.setText(new String(b));
                    
                    
                        
                        
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error while getting file!");
                }
                
                oos.close();
                oin.close();
                 soc.close();
           }
           
               
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
                
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            if (jTextArea1.getText().trim().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Select the file to download!");
            }
            else
            {
                String fname=jComboBox1.getSelectedItem().toString().trim();
                String data=jTextArea1.getText().trim();
                
                FileOutputStream fout=new FileOutputStream(fname);
                fout.write(data.getBytes());
                fout.close();
                
                String reply1=new sendblock().addblock(uname,"DOWNLOAD",fname);
                      
                    if (reply1.equals("SUCCESS")) //block added in blockchain server
                       JOptionPane.showMessageDialog(this,"Block successfully added to blockchain server!");
                    else
                       JOptionPane.showMessageDialog(this,"Block creation failed!");
                
                JOptionPane.showMessageDialog(this,"File "+ fname+" successfully downloaded!");
                
                Desktop d=Desktop.getDesktop();
                d.open(new File(fname));
                
            }
                
        }
        catch(Exception e)
        {
            System.out.println(e);
            e.printStackTrace();
        }
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
